version: '3'
services:
  envoy:
    image: envoyproxy/envoy-dev:da9962b60bd7bea6eccd5f2e00965585d1119bfd
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - '9901:9901'
      - '8080:8080'
  redis:
    image: bitnami/redis
    volumes:
      - ./redis:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
